import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          width: "100vw",
          height: "100vh",
          boxSizing: "border-box",
        }}
      >
        {children}
      </body>
    </html>
  );
}
